name: Deploy Blog to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Minificar HTML, CSS y JavaScript (opcional)
    - name: Minify HTML, CSS, and JavaScript
      run: |
        sudo apt-get install -y html-minifier uglifycss uglify-js
        find . -name "*.html" -exec html-minifier --collapse-whitespace --remove-comments --minify-js --minify-css {} \;
        find . -name "*.css" -exec uglifycss {} --output {} \;
        find . -name "*.js" -exec uglifyjs {} -o {} \;

    # 3. Optimizar imágenes (PNG y GIF)
    - name: Optimize images
      run: |
        sudo apt-get install optipng gifsicle
        find . -iname '*.png' -exec optipng -o7 {} \;
        find . -iname '*.gif' -exec gifsicle -O3 --batch {} \;

    # 4. Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: .  # Aquí publica directamente desde el directorio raíz
