name: Deploy blog to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout repository
    - name: Checkout code
      uses: actions/checkout@v2

    # 2. Set up Node.js for tools (no dependencias)
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    # 3. Minificar HTML (opcional, si tienes HTML generado dinámicamente)
    - name: Minify HTML
      run: |
        find . -name "*.html" -exec html-minifier --collapse-whitespace --remove-comments --remove-attribute-quotes --minify-js --minify-css {} \;

    # 4. Optimización de imágenes con una acción alternativa (optipng y gifsicle)
    - name: Optimize images
      run: |
        sudo apt-get install optipng gifsicle
        find . -iname '*.png' -exec optipng -o7 {} \;
        find . -iname '*.gif' -exec gifsicle -O3 --batch {} \;

    # 5. Generar el sitemap (opcional, si tienes múltiples páginas)
    - name: Generate sitemap
      run: |
        npm install -g sitemap-generator-cli
        sitemap-generator https://your-website-url.com -o sitemap.xml

    # 6. Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
